# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [10]:
from numpy import random

In [16]:
np.random.rand()

0.4523770547457967

0.951962806590464

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [17]:
np.random.randn(25)

array([ 0.42174484, -0.7871044 , -1.13144885,  0.24872615, -0.29836252,
       -0.22514869,  0.05698081,  0.036332  , -0.05899089,  0.07994682,
        1.2014132 ,  2.06377654, -0.70920329,  0.0537246 , -0.76327772,
        0.40150825,  0.82613639,  1.25630348, -2.25815951,  0.14197028,
        0.9680096 , -0.82657732,  0.02645653,  0.21678455, -0.51822118])

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

#### Create the following matrix:

In [19]:
np.random.rand(100).reshape(20, 5)

array([[0.4228702 , 0.31895727, 0.14117077, 0.66267315, 0.24021858],
       [0.52399725, 0.2009911 , 0.26656469, 0.05637381, 0.29589783],
       [0.58811904, 0.91028372, 0.27251738, 0.73919805, 0.21398182],
       [0.86242038, 0.13773981, 0.44987097, 0.23062654, 0.56860079],
       [0.2167449 , 0.84176091, 0.95175243, 0.48187066, 0.06943517],
       [0.54704268, 0.02514548, 0.05584823, 0.12588774, 0.3255359 ],
       [0.80663796, 0.20294561, 0.56453691, 0.24357702, 0.40340177],
       [0.95082467, 0.96220829, 0.77339373, 0.96031954, 0.60360886],
       [0.86496456, 0.46170758, 0.75447684, 0.85939628, 0.38336935],
       [0.87153416, 0.85837441, 0.79817834, 0.56351264, 0.84363471],
       [0.49907165, 0.59313045, 0.6258069 , 0.89100192, 0.71028984],
       [0.24149157, 0.89689685, 0.33595135, 0.46846888, 0.56163244],
       [0.95993786, 0.78256778, 0.35502097, 0.57710519, 0.88399552],
       [0.47085954, 0.56572677, 0.26684211, 0.91681309, 0.89325268],
       [0.60234599, 0.77285137, 0.

array([[0.47325185, 0.31687143, 0.92315798, 0.00944664, 0.60830481,
        0.47149244, 0.79730795, 0.72197131, 0.84899411, 0.01795184],
       [0.57900727, 0.34508023, 0.48016543, 0.99348081, 0.06871019,
        0.31279884, 0.55701429, 0.98209127, 0.51928253, 0.92712081],
       [0.62565429, 0.80846004, 0.72829608, 0.34980847, 0.2327374 ,
        0.47676367, 0.38464416, 0.5483618 , 0.63090987, 0.36734357],
       [0.47504607, 0.6957894 , 0.10041094, 0.83642747, 0.109461  ,
        0.37350456, 0.18693862, 0.83277221, 0.27106925, 0.39778378],
       [0.77510687, 0.78144895, 0.35545704, 0.23139187, 0.87181658,
        0.46630382, 0.31662621, 0.2948518 , 0.52938676, 0.97693867],
       [0.04279191, 0.7529686 , 0.27601624, 0.037062  , 0.49163982,
        0.08637015, 0.17704648, 0.02366608, 0.19145927, 0.38069567],
       [0.25340951, 0.8950335 , 0.23507032, 0.18247659, 0.57591731,
        0.97841964, 0.89265674, 0.48002304, 0.40070118, 0.50849625],
       [0.6112385 , 0.29325072, 0.0759372

#### Create an array of 20 linearly spaced points between 0 and 1:

In [20]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [24]:
a=np.arange(1, 26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [26]:
a[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [27]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [28]:
a[3,4]

20

20

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [37]:
a[:-2, 1]

array([ 2,  7, 12])

array([[ 2],
       [ 7],
       [12]])

In [38]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [40]:
a[-1]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [41]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [43]:
a[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [44]:
a.sum()

325

325

#### Get the standard deviation of the values in mat

In [45]:
a.std()

7.211102550927978

7.211102550927978

#### Get the sum of all the columns in mat

In [46]:
a.sum(axis=0)

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])

# Great Job!